jobs:
- template: scripts/templates/azure-pipeline-linux.yml
  parameters:
      packageListsFile: qt-packages-linux.txt
- template: scripts/templates/azure-pipeline-windows.yml
  parameters:
      packageListsFile: qt-packages-windows.txt
- template: scripts/templates/azure-pipeline-macos.yml
  parameters:
      packageListsFile: qt-packages-macos.txt
- template: scripts/templates/azure-pipeline-android.yml
  parameters:
      packageListsFile: qt-packages-android.txt
