parameters:
    packageListsFile: ''
jobs:
- job: x64_osx
  pool:
    vmImage: 'macOS-10.13'
  variables:
    packageListsFile: ${{ parameters.packageListsFile }}
  steps:
  - script: |
      brew install gcc6
      ./bootstrap-vcpkg.sh
      ./vcpkg install $(cat $packageListsFile)
      ./vcpkg export --output=x64-osx --zip $(cat $packageListsFile)
    displayName: 'make'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'x64-osx.zip'
