parameters:
    packageListsFile: ''
    triplet: 'x64-osx'
    jobName: 'x64_osx'
jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: 'macOS-10.13'
  variables:
    packageListsFile: ${{ parameters.packageListsFile }}
    VCPKG_DEFAULT_TRIPLET: ${{ parameters.triplet }}
  steps:
  - script: |
      brew install gcc6
      ./bootstrap-vcpkg.sh
      ./vcpkg install $(cat $packageListsFile)
      ./vcpkg export --output=$VCPKG_DEFAULT_TRIPLET --zip $(cat $packageListsFile)
    displayName: 'make'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '${{ parameters.triplet }}.zip'
