parameters:
    jobName: ''
    packageListsFile: ''
    triplet: ''
jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    VCPKG_DEFAULT_TRIPLET: ${{ parameters.triplet }}
    packageListsFile: ${{ parameters.packageListsFile }}
  steps:
  - powershell: |
      ./bootstrap-vcpkg.bat
      ./vcpkg install $(cat $env:packageListsFile)
      ./vcpkg export --output=$env:VCPKG_DEFAULT_TRIPLET --zip $(cat $env:packageListsFile)
    displayName: 'make'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '${{ parameters.triplet }}.zip'

